---
title: "QUINIELA RUSIA 2018"
subtitle: "Sígueme A 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    # vertical_layout: scroll
    logo: football-soccer-ball-48-183228.png
    theme: cerulean
    source_code: "https://github.com/adfmb/quinielaRSA2018"
runtime: shiny
---

Resultados Fase de Grupos {data-orientation=columns}
=======================================================================
  
  Column
-------------------------------------
  
```{r}
source("utils/importacion.R")
```


### 
  
```{r}

partido1<-61
partido2<-62

fluidRow(
  
  column(4,
         h2(paste0("W",partido1))
  ),
  
  column(4,
         numericInput(paste0("W",partido1,"E1"),
                      renderUI(
                        if(listaSemis()!="MENSAJE SIN CONCLUIR FASE DE CUARTOS"){
                          if(!is.null(listaSemis()$data_resumenEquipos)){
                            paste0(e61()[1])}
                        }else{
                          tags$span(style="color:red",
                                    alarmaSemis##,unique(lista2A()$data_EquipoPartido$Grupo),"!")
                          )
                        }
                      ),
                      min=0, max=100, value=0,step=1,
                      width = '100px')
  )
)
fluidRow(
  
  column(4,
         tags$div(
           HTML(paste(tags$span(style="color:white", "----   "), sep = ""))
         )),
  
  column(4,
         tags$div(
           HTML(paste(tags$span(style="color:white", "----"),tags$h3(style="color:red", "vs"), sep = ""))
         ))
  
)

fluidRow(
  column(4,
         h2(paste0("W",partido2))
  ),
  
  column(4,
         numericInput(paste0("W",partido2,"E1"),
                      renderUI(
                        if(listaSemis()!="MENSAJE SIN CONCLUIR FASE DE CUARTOS"){
                          if(!is.null(listaSemis()$data_resumenEquipos)){
                            paste0(e62()[1])}
                        }else{
                          tags$span(style="color:red",
                                    alarmaSemis##,unique(lista2A()$data_EquipoPartido$Grupo),"!")
                          )
                        }
                      ),
                      min=0, max=100, value=0,step=1,
                      width = '100px')
  )
)
```

<!-- Row -->
  <!-- ------------------------------------- -->
  
### TERCER LUGAR
  
```{r}
partido1<-61
partido2<-62

fluidRow(
  
  column(4,
         h2(paste0("L",partido1))
  ),
  
  column(4,
         numericInput(paste0("W",partido1,"E2"),
                      renderUI(
                        if(listaSemis()!="MENSAJE SIN CONCLUIR FASE DE CUARTOS"){
                          if(!is.null(listaSemis()$data_resumenEquipos)){
                            paste0(e61()[2])}
                        }else{
                          tags$span(style="color:red",
                                    alarmaSemis##,unique(lista2A()$data_EquipoPartido$Grupo),"!")
                          )
                        }
                      ),
                      min=0, max=100, value=0,step=1,
                      width = '100px')
  )
)
fluidRow(
  
  column(4,
         tags$div(
           HTML(paste(tags$span(style="color:white", "----   "), sep = ""))
         )),
  
  column(4,
         tags$div(
           HTML(paste(tags$span(style="color:white", "----"),tags$h3(style="color:red", "vs"), sep = ""))
         ))
  
)

fluidRow(
  column(4,
         h2(paste0("L",partido2))
  ),
  
  column(4,
         numericInput(paste0("W",partido2,"E2"),
                      renderUI(
                        if(listaSemis()!="MENSAJE SIN CONCLUIR FASE DE CUARTOS"){
                          if(!is.null(listaSemis()$data_resumenEquipos)){
                            paste0(e62()[2])}
                        }else{
                          tags$span(style="color:red",
                                    alarmaSemis##,unique(lista2A()$data_EquipoPartido$Grupo),"!")
                          )
                        }
                      ),
                      min=0, max=100, value=0,step=1,
                      width = '100px')
  )
)
```


Column {data-width=180}
-------------------------------------
  
### G A N A D O R {data-height=1200}

```{r}
library(shinyjs)

dataW1s<-reactive({data.frame("Codigo"=c("W_64_E1","W_64_E2",
                                         "W_63_E1","W_63_E2"),
                              "Equipo"=c(paste0(e61()[1]),paste0(e62()[1]),
                                         paste0(e61()[2]),paste0(e62()[2]))
)
  # eventReactive({ input$buttonA input$buttonB input$buttonC input$buttonD input$buttonE input$buttonF input$buttonG input$buttonH}
})


listaFinales<-eventReactive(input$buttonFinales,{
  
  if(vFinales$OK[1] & vFinales$OK[2]){
    # print("holi")
    calcula_Goles(vectorgoles=c(input[["W61E1"]],input[["W62E1"]],#input[[paste0("E1",Grupo1)]],
                                input[["W61E2"]],input[["W62E2"]]),
                  data=dataW1s()
    )
  }else{
    "MENSAJE SIN CONCLUIR FASE DE SEMIS"
  }
})
fluidRow(
  
  column(7,
         actionButton("buttonFinales"," ¡TU GANADOR! ", 
    style="color: #0066ff;background-image:-webkit-linear-gradient(#fff, #fff 60%, #f5f5f5)")
  ),
  
  column(7,
         renderTable({
           if(listaFinales()=="MENSAJE SIN CONCLUIR FASE DE SEMIS"){
             m<-matrix("FASE DE SEMIFINALES SIN CONCLUIR CORRECTAMENTE")
             colnames(m)<-"¡¡¡O.O!!!!"
             m
           }else if(!is.null(listaFinales()$data_EquipoPartido)){
             if(lista2A()$marcaBoton & lista2B()$marcaBoton){
               if(listaFinales()$marcaBoton){
                 if(sum(listaFinales()$data_EquipoPartido$Empate)==0){
                   pais<-listaFinales()$data_EquipoPartido[1:2,c("Grupo","Partido","Equipo")]
                   m<-as.matrix(pais$Equipo[pais$Partido==64])
                   colnames(m)<-"¡¡¡TU CAMPEÓN!!!!"
                   m
                   #[,listaFinales()$data_EquipoPartido$Partido==64])
                 }else{
                   m<-matrix("</3 Cámbialo porfiiiiis")
                   colnames(m)<-"¡¡¡NO MAMAR QUE PUSISTE EMPATES!!!!"
                   m
                 }
                 
               }else{
                 m<-matrix("Por favor revisa que las cantidades de sean correctas :O")
                 colnames(m)<-"¡¡¡AGUAS!!!!"
                 m
               }
             }else{
               m<-matrix("Por favor revisa que las cantidades de Primera Fase sean correctas :O")
               colnames(m)<-"¡¡¡AGUAS!!!!"
               m
             }
             
           }else{
             m<-matrix("Por favor revisa que las cantidades ingresadas sean correctas")
             colnames(m)<-"¡¡¡AGUAS!!!!"
             m
           }
           
         })
         
  )
)

fluidRow(
  
  column(7,
         renderTable({
           if(listaFinales()=="MENSAJE SIN CONCLUIR FASE DE SEMIS"){

           }else if(!is.null(listaFinales()$data_EquipoPartido)){
             if(lista2A()$marcaBoton & lista2B()$marcaBoton){
               if(listaFinales()$marcaBoton){
                 if(sum(listaFinales()$data_EquipoPartido$Empate)==0){
                   pais<-listaFinales()$data_EquipoPartido[3:4,c("Grupo","Partido","Equipo")]
                   m<-as.matrix(pais$Equipo[pais$Partido==64])
                   colnames(m)<-"¡¡¡TU SEGUNDO LUGAR!!!!"
                   m
                   #[,listaFinales()$data_EquipoPartido$Partido==64])
                  }}}}
         })
  )
)

fluidRow(
  
  column(7,
         renderTable({
           if(listaFinales()=="MENSAJE SIN CONCLUIR FASE DE SEMIS"){

           }else if(!is.null(listaFinales()$data_EquipoPartido)){
             if(lista2A()$marcaBoton & lista2B()$marcaBoton){
               if(listaFinales()$marcaBoton){
                 if(sum(listaFinales()$data_EquipoPartido$Empate)==0){
                   pais<-listaFinales()$data_EquipoPartido[1:2,c("Grupo","Partido","Equipo")]
                   m<-as.matrix(pais$Equipo[pais$Partido==63])
                   colnames(m)<-"¡¡¡TU TERCER LUGAR!!!!"
                   m
                   #[,listaFinales()$data_EquipoPartido$Partido==64])
                  }}}}
         })
  )
)
```

### Paso Final

```{r}
vDownload <- reactiveValues(OK = c(F,F))

observeEvent(input$buttonFinales, {
  if(listaFinales()=="MENSAJE SIN CONCLUIR FASE DE SEMIS"){
    vDownload$OK[1] <- F
    vDownload$OK[2] <- F
  }else{
    vDownload$OK[1] <- listaFinales()$marcaBoton
    vDownload$OK[2] <- sum(listaFinales()$data_EquipoPartido$Empate)==0
  }
})

fluidRow(
  # column(5,
                renderUI({
                    downloadButton("downloadData1", "Descarga tu quiniela")
                })
  # )
)

data1F<-reactive({
  pegar1Fase<-pegar1Fase(lista2A()$data_EquipoPartido,
                         lista2B()$data_EquipoPartido,
                         lista2C()$data_EquipoPartido,
                         lista2D()$data_EquipoPartido,
                         lista2E()$data_EquipoPartido,
                        lista2F()$data_EquipoPartido, 
                        lista2G()$data_EquipoPartido,
                        lista2H()$data_EquipoPartido,
                        lista8vos()$data_EquipoPartido,
                        lista4s()$data_EquipoPartido,
                        listaSemis()$data_EquipoPartido,
                        listaFinales()$data_EquipoPartido,
                        input$nombre_equipo,
                        input$nombre_part,
                        input$folio,
                        input$correo)
})
output$downloadData1 <- downloadHandler(
    filename = function() { 
      paste(Sys.time(),"_",input$correo,"_",input$folio,'.csv', sep='') 
    },
    content = function(file) {
      write.csv(data1F(), file, sep = ".csv",
        row.names = FALSE)
    }
  )

# renderTable(lista2A()$data_EquipoPartido)


```