---
title: "QUINIELA RUSIA 2018"
subtitle: "Sígueme A 2018"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
# vertical_layout: scroll
logo: football-soccer-ball-48-183228.png
theme: cerulean
source_code: "https://github.com/adfmb/quinielaRSA2018"
# runtime: shiny
---
  
Cuartos de Final {data-orientation=columns data-navmenu="Resultados del día"}
=======================================================================
  
Column  {data-width=800}
-------------------------------------
  
```{r, include=FALSE}
# options(shiny.sanitize.errors = TRUE)
library(dplyr)
library(knitr)
library(DT)
library(googlesheets)
source("utils/importacion.R")
source("utils/generate_gbs_F02.R")
source("utils/streamingmatch_F02.R")
source("utils/global.R")
alldocs<-importa_alldocs(F)#readRDS("data/alldocs.rds")
# resultados_reales<-read.csv("data/resultados_reales.csv",header=T)
for_gs <- gs_title("resultados_reales")
resultados_reales <- gs_read(ss)
resultados_reales<-resultados_reales%>%
  mutate_at(vars(Grupo,Partido,E1E2,Equipo_gsub,Codigo2,status_juego),.funs = funs(as.character))
```

```{r}
# gbs2<-generate_gbs_F02(alldocs = alldocs,resultados_reales = resultados_reales)
```

```{r}
# sm2<-streamingmatch_F02(alldocs = alldocs,resultados_reales = resultados_reales,fase="Cuartos")
```


### Partidos en juego {data-height=400}
```{r echo = FALSE, results = 'asis'}
# if(nrow(sm2$show_tblsm)==0){
#   datatable(sm2$show_tblsm)
# }else{
#   kable(sm2$show_tblsm%>%select(-Partido))
# }
```

### Pronósticos {data-height=800}
```{r echo = FALSE, results = 'asis'}
library(knitr)
# kable(sm2$sm%>%
#         # select(-Partido)%>%
#         rename(Concursante=nomconcursante))
datatable(gbs2$gb_nomb%>%arrange(desc(Suma_Puntos_Partido),desc(Suma_Puntos_1erL),desc(Suma_Puntos_2doL),desc(Suma_Puntos_3erL))%>%ungroup())
# rename(Concursante=nomconcursante)
```

Column {data-width=400 .tabset .tabset-fade}
-------------------------------------
  
```{r}
datatable(gbs$gb_nomb%>%arrange(desc(Suma_Puntos_Partido),desc(Suma_Puntos_1erL),desc(Suma_Puntos_2doL),desc(Suma_Puntos_3erL))%>%ungroup())
```

### Tabla de Posiciones Grupo A
```{r}
datatable(gbs$gb_nomb%>%arrange(desc(Suma_Puntos_Partido),desc(Suma_Puntos_Marcador),desc(Suma_Puntos_Resultado))%>%ungroup())
# }else{
#   kable(tb1)
# }
```

### Tabla de Posiciones Grupo B
```{r}

```
