---
title: "QUINIELA RUSIA 2018"
subtitle: "Sígueme A 2018"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
# vertical_layout: scroll
logo: football-soccer-ball-48-183228.png
theme: cerulean
source_code: "https://github.com/adfmb/quinielaRSA2018"
runtime: shiny
---
  
Primer, Segundo y Tercer Lugar {data-orientation=columns data-navmenu="Resultados del día"}
=======================================================================
  
Column  {data-width=800}
-------------------------------------
  
```{r, include=FALSE}
# options(shiny.sanitize.errors = TRUE)
if(!exists("alldocs")){
  library(dplyr)
  library(knitr)
  library(DT)
  source("utils/importacion.R")
  source("utils/global.R")
  alldocs<-importa_alldocs(F)#readRDS("data/alldocs.rds")
}

if(!exists("resultados_reales")){
  library(googlesheets)
  # resultados_reales<-read.csv("data/resultados_reales.csv",header=T)
  for_gs <- gs_title("resultados_reales")
  resultados_reales <- gs_read(ss)
  resultados_reales<-resultados_reales%>%
    mutate_at(vars(Grupo,Partido,E1E2,Equipo_gsub,Codigo2,status_juego),.funs = funs(as.character))
}

```

```{r}
if(!exists("gbs2")){
  source("utils/generate_gbs_F02.R")
  gbs2<-generate_gbs_F02(alldocs = alldocs,resultados_reales = resultados_reales)
}

```

```{r}
source("utils/streamingmatch_F02.R")
sm2<-streamingmatch_F02(alldocs = alldocs,resultados_reales = resultados_reales,fase=c("Tercer","Final"))

```


### Partidos en juego {data-height=400}
```{r echo = FALSE, results = 'asis'}
if(nrow(sm2$show_tblsm)==0){
  datatable(sm2$show_tblsm)
}else{
  kable(sm2$show_tblsm%>%select(-Partido)%>%rename(Fase=Codigo2))
}
```

### Pronósticos {data-height=800}
```{r echo = FALSE, results = 'asis'}
library(knitr)
# kable(sm2$sm%>%
#         # select(-Partido)%>%
#         rename(Concursante=nomconcursante))
datatable(sm2$sm%>%
            ungroup()%>%
            select(-nomconcursante,
                   -Grupo,
                   -Resultado_correcto_partido_Perdedor#,
                   # -Puntos_primlugar,
                   # -Puntos_seglugar,
                   # -Puntos_terlugar
                   )%>%
            rename(Folio=folio)%>%
            rename(Puntos_por_ganadores=Puntos_Partido)%>%
            rename(Fase=Codigo2)%>%
            rename(`Ganadores acertados`=Ganadores_Fase_acertados)%>%
            rename(`Puntos por ganadores`=Puntos_por_ganadores)%>%
            rename(`Puntos por 1er Lugar`=Puntos_primlugar)%>%
            rename(`Puntos por 2do Lugar`=Puntos_seglugar)%>%
            rename(`Puntos por 3er Lugar`=Puntos_terlugar),
          extensions = 'FixedColumns',
          options=list(
            dom = 'RMDCT<"clear">lfrtip',
            searchHighlight = TRUE,
            # tableTools = list(sSwfPath = copySWF('www')),
            pageLength = 10,
            scrollX = TRUE,
            fixedColumns =list(leftColumns=2)
          ),
          rownames=F)#%>%
# rename(Concursante=nomconcursante)
```

Column {data-width=600 .tabset .tabset-fade}
-------------------------------------
  
```{r}
# renderTable({
#   
#   as.matrix(gbs$gb_nomb)
#   
#   })
tb1<-gbs2$gb_nomb%>%arrange(desc(Suma_Puntos_Partido),desc(Suma_Puntos_1erL),desc(Suma_Puntos_2doL),desc(Suma_Puntos_3erL))%>%ungroup()
names(tb1)<-c("Concursante","folio","Ganadores Acertados","Pts x 1er Lugar","Pts x 2do Lugar","Pts x 3er Lugar","Pts Fase Eliminación")
# datatable(tb1,
#           extensions = 'FixedColumns',
#           options=list(
#             dom = 'RMDCT<"clear">lfrtip',
#             searchHighlight = TRUE,
#             # tableTools = list(sSwfPath = copySWF('www')),
#             pageLength = 15,
#             scrollX = TRUE,
#             fixedColumns =list(leftColumns=2)
#             ),
#           rownames=F)
# if(nrow(tb1)==0){
```

### Tabla de Posiciones Grupo A
```{r}
datatable(tb1%>%filter(grepl("A",folio) | grepl("a",folio)))#%>%select(-one_of(c("Pts x 1er Lugar","Pts x 2do Lugar","Pts x 3er Lugar"))))
# }else{
#   kable(tb1)
# }
```

### Tabla de Posiciones Grupo B
```{r}
datatable(tb1%>%filter(grepl("B",folio) | grepl("b",folio)))#%>%select(-one_of(c("Pts x 1er Lugar","Pts x 2do Lugar","Pts x 3er Lugar"))))
# }else{
#   kable(tb1)
# }
```
