---
title: "QUINIELA RUSIA 2018"
subtitle: "Sígueme A 2018"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
# vertical_layout: scroll
logo: football-soccer-ball-48-183228.png
theme: cerulean
source_code: "https://github.com/adfmb/quinielaRSA2018"
runtime: shiny
---
  
Puntuaciones acumuladas {data-navmenu="Resultados del día"}
=======================================================================
```{r, include=FALSE}
# options(shiny.sanitize.errors = TRUE)
if(!exists("alldocs")){
  library(dplyr)
  library(knitr)
  library(DT)
  source("utils/importacion.R")
  source("utils/global.R")
  alldocs<-importa_alldocs(F)#readRDS("data/alldocs.rds")
}

if(!exists("resultados_reales")){
  library(googlesheets)
  # resultados_reales<-read.csv("data/resultados_reales.csv",header=T)
  for_gs <- gs_title("resultados_reales")
  resultados_reales <- gs_read(ss)
  resultados_reales<-resultados_reales%>%
    mutate_at(vars(Grupo,Partido,E1E2,Equipo_gsub,Codigo2,status_juego),.funs = funs(as.character))
}

```

```{r}
if(!exists("gbs")){
  source("utils/generate_gbs_F01.R")
  gbs<-generate_gbs_F01(alldocs = alldocs,resultados_reales = resultados_reales)
}

if(!exists("gbs2")){
  source("utils/generate_gbs_F02.R")
  gbs2<-generate_gbs_F02(alldocs = alldocs,resultados_reales = resultados_reales)
}

gb_total<-gbs$gb_nomb%>%rename(Puntos_Partido_1F=Suma_Puntos_Partido)%>%left_join(gbs2$gb_nomb%>%rename(Puntos_Partido_2F=Suma_Puntos_Partido))
gb_total<-gb_total%>%
  mutate(Puntos_totales=Puntos_Partido_1F+Puntos_Partido_2F)%>%
  arrange(desc(Puntos_totales),desc(Puntos_Partido_1F),desc(Puntos_Partido_2F))%>%
            rename(Folio=folio)%>%
            rename(`Puntos por resultados 1era Fase`=Suma_Puntos_Resultado)%>%
            rename(`Puntos por marcadores 1era Fase`=Suma_Puntos_Marcador)%>%
            rename(`Puntos totales por 1era Fase`=Puntos_Partido_1F)%>%
            rename(`Ganadores acertados de 2da Fase`=Ganadores_TotalesF02_acertados)%>%
            rename(`Puntos por 1er Lugar`=Suma_Puntos_1erL)%>%
            rename(`Puntos por 2do Lugar`=Suma_Puntos_2doL)%>%
            rename(`Puntos por 3er Lugar`=Suma_Puntos_3erL)%>%
            rename(`Puntos totales por 2da Fase`=Puntos_Partido_2F)%>%
            rename(`Puntos totales`=Puntos_totales)
```

Row
-------------------------------------
### Tabla de Posiciones Grupo A
```{r}
datatable(gb_total%>%filter(grepl("A",Folio) | grepl("a",Folio)),
          options=list(
            pageLength = 5)
          )#%>%select(-one_of(c("Pts x 1er Lugar","Pts x 2do Lugar","Pts x 3er Lugar"))))
# }else{
#   kable(tb1)
# }
```

Row
-------------------------------------
### Tabla de Posiciones Grupo B
```{r}
datatable(gb_total%>%filter(grepl("B",Folio) | grepl("b",Folio)),
          options=list(
            pageLength = 5)
          )#%>%select(-one_of(c("Pts x 1er Lugar","Pts x 2do Lugar","Pts x 3er Lugar"))))
# }else{
#   kable(tb1)
# }
```
