---
title: "QUINIELA RUSIA 2018"
subtitle: "Sígueme A 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    logo: Sigueme05.png
    theme: cerulean
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
options(warn = 0)
```

Sidebar {.sidebar data-width=250}
=======================================================================

\newline
\newline
\newline
\newline
\newline
\newline
\newline
\newline
\newline
\newline

```{r fig.width=2, fig.height=2,echo=FALSE}
library(jpeg)
library(grid)
img <- readJPEG("russia01.jpg")

grid.raster(img)
```


Dashboard
=======================================================================

Row
-----------------------------------------------------------------------


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

